# Generated by Django 4.2.4 on 2023-08-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('value', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, 'その他')])),
                ('birthday', models.DateField()),
                ('adress', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('evaluator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_user', to='app.matching')),
                ('rater_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rater_user', to='app.matching')),
            ],
        ),
        migrations.AddField(
            model_name='matching',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_user', to='app.user'),
        ),
        migrations.AddField(
            model_name='matching',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item'),
        ),
        migrations.AddField(
            model_name='matching',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_user', to='app.user'),
        ),
        migrations.CreateModel(
            name='Item_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tag')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sented_at', models.DateTimeField(auto_now_add=True)),
                ('matching_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.matching')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
        ),
    ]
