# Generated by Django 4.2.4 on 2023-08-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_chat_sender_id_chat_receiver_chat_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='matching_id',
        ),
    ]
