# Generated by Django 4.2.4 on 2023-08-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_chat_matching_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item_tag',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item_tag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='evaluator_id',
            new_name='evaluator',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rater_id',
            new_name='rater',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
