# Generated by Django 4.2.4 on 2023-08-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_chat_receiver_chat_matching_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='text',
            new_name='message',
        ),
    ]
